server:
  port: 8092
  servlet:
    context-path: /property-view

spring:
  application:
    name: property-view
  profiles:
    active: h2
  jackson:
    default-property-inclusion: always
    deserialization:
      fail-on-unknown-properties: false
    serialization:
      write-dates-as-timestamps: false
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXTS:default}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
